### ISSUE TITLE
ManagedChannel configuration injection failure when eager single initialization is set

### ISSUE THREAD

**Issue by paulolieuthier** [micronaut-projects/micronaut-grpc#360]
ManagedChannel configuration injection fails when the application is run with eager single initialization.

### Steps to Reproduce

1. `mn create-grpc-app example-project`.
2. Add `.eagerInitSingletons(true)` to Micronaut initialization.
3. Try to run the application.

### Expected Behaviour

The application should run just fine.

### Actual Behaviour

Exception is thrown:

```
$ ./gradlew run

> Task :run FAILED
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

17:07:01.586 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration] could not be loaded: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration] could not be loaded: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1568)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2907)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at micronaut.bug.Application.main(Application.java:9)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [name] of class: io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new GrpcDefaultManagedChannelConfiguration([String name],Environment env,ExecutorService executorService)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1041)
        at io.micronaut.grpc.channels.$GrpcDefaultManagedChannelConfigurationDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2294)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1562)
        ... 6 common frames omitted
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2412)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
        ... 12 common frames omitted

FAILURE: Build failed with an exception.
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.5.4
- **JDK Version:** 11.0.11

**Comment by paulolieuthier** [comment]
@graemerocher could you point me in the right direction so I can work on a fix?

**Comment by graemerocher** [comment]
Seems like a bug in core
