### ISSUE TITLE
Micronaut 4.2.0 breaks grpc services

### ISSUE THREAD

**Issue by krickert** [micronaut-projects/micronaut-grpc#805]
### Expected Behavior

GRPC serialization back to a client reply should work.

**NOTE: this does not happen in the projects below because the 3rd party patch was applied to them.  This allows the grpc services to work in micronaut 4.2.0. **

### Actual Behaviour

GRPC throws exceptions

## Examples

I have a number of simple grpc projects in my repo that run micronaut services.  Once I bumped the service to 4.2.0, the OOTB functionality no longer works for grpc blocking stubs and regular stubs.  Below are the URLs to the projects (there's one dependent project as well, which matches the grpc running version of 1.59.0.

The sample applications where this depends on grpc servers are as follows:
https://github.com/krickert/search_indexer/tree/master/services/grpc-services/grpc-nlp-service
https://github.com/krickert/search_indexer/tree/master/services/grpc-services/grpc-vectorizer-service
https://github.com/krickert/search_indexer/tree/master/services/pipeline-processor

The tests that break are any test that uses the standard grpc transport.

## Barebones test (follows the same as the guide docs)

Here is the most barebones test:

https://github.com/krickert/grpc_micronaut_420_broken_example

This uses jdk17 (amazon latest), maven 3.9.5 on the latest ubuntu desktop.  Also repeatable on jdk17 on osx.  Didn't test anywhere else yet since I see consistent results.

## output from test

```
[ERROR] com.broken.grpc.GrpcExampleTest.testServerEndpoint -- Time elapsed: 0.165 s <<< ERROR!
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at com.broken.grpc.GrpcExampleServiceGrpc$GrpcExampleServiceBlockingStub.send(GrpcExampleServiceGrpc.java:160)
	at com.broken.grpc.GrpcExampleTest.testServerEndpoint(GrpcExampleTest.java:79)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
	at io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:157)
	at io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:114)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.UnsupportedOperationException
	at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
The above is returned for the non-blocking test... 

The following is returned for the blocking test:
```
11:19:53.868 [io-executor-thread-2] ERROR com.broken.grpc.GrpcExampleTest - Not implemented
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException: null
	at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

In both instances, the service is called, it seems the serialization is the broken part.

### Steps To Reproduce

1. Linux ubuntu
2. jdk17 / maven 3.9.5
3. `git clone https://github.com/krickert/grpc_micronaut_420_broken_example.git`
4. `cd grpc_micronaut_420_broken_example`
5. `mvn test`

### Environment Information

Latest ubuntu
jdk 17 
```
~/IdeaProjects/grpc_micronaut_420_broken_example$ java -version
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.9.8.1 (build 17.0.9+8-LTS, mixed mode, sharing)
```

### Example Application

https://github.com/krickert/grpc_micronaut_420_broken_example

### Version

4.2.0

**Comment by krickert** [comment]
From my debugger:

If you use the non-blocking client - the reply does happen but the stream observer throws an onError() as well.  But the onNext() is called, so replies do happen, but an error occurs with each call.

The blocking stub throws an exception all the time.

Any help is greatly appreciated.

**Comment by krickert** [comment]
I updated the test to have fewer dependencies.  Same error.

**Comment by sdelamo** [comment]
there is a necessary release in grpc-java we are waiting for https://github.com/grpc/grpc-java/pull/10663

**Comment by krickert** [comment]
Bummer - so the release breaks GRPC but we can't fix it until they fix the bug?  Why not just downgrade the grpc version since the entire framework is busted with the most recent version?

**Comment by krickert** [comment]
I'm installing the snapshot of grpc-java and I'll let you know if the patch fixes this.

**Comment by krickert** [comment]
OK - the patch makes it work.  I just took the patch you outlined and applied it to my code.  I'll have to make a quick patch project for these projects, but it'll allow me to use my projects on the latest micronaut then.

I'll commit the patch I made to the project.  I'm just adding the same patch and it shows that the tests work now.

Feel free to grab the test I wrote as a part of your tests in the future.

**Comment by krickert** [comment]
Just added the "patch"; I took the java code from the upcoming grpc release and just added it to the jar file.  Because it's in the same jar, the patch version will always win.

**Comment by jeremyg484** [comment]
> Bummer - so the release breaks GRPC but we can't fix it until they fix the bug? Why not just downgrade the grpc version since the entire framework is busted with the most recent version?

@krickert Yes, unfortunately downgrading the GRPC version doesn't fix the issue, because the older implementations also have the same unimplemented method. The issue appears now because Netty 4.1.101 now invokes the missing `isEmpty` method whereas it they did not in version 4.1.100 and earlier. I believe temporarily downgrading to Netty 4.1.100 would also work until GRPC releases the patch in 1.60 which they say will happen on Nov 28th.

**Comment by krickert** [comment]
Yesterday the latest grpc version fixes this.  However, it breaks it in other ways, from what I can see.  I keep getting an error for io.grpc.internal.AbstractServerImplBuilder not found when updating the library
